"""init

Revision ID: f735bf70adb5
Revises: 
Create Date: 2023-08-04 11:18:23.844089

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f735bf70adb5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metrics_path"), "metrics", ["path"], unique=False)
    op.create_index(op.f("ix_metrics_service_name"), "metrics", ["service_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_service_name"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_path"), table_name="metrics")
    op.drop_table("metrics")
    # ### end Alembic commands ###
